name: 'Nomuken - Setup packer'
description: 'set up packer cli for github actions runner'
author: 'nomuken'
inputs:
  github_token:
    required: true
    description: 'Your GitHub token(It will set the GitHub Actions token). It is for searching valid Packer versions from GitHub repository (hashicorp/packer).'
    default: '${{github.token}}'
  packer_version:
    required: true
    description: 'The version of Packer CLI. It can only set "latest" or version name like "v1.2.3".'
    default: "latest"
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'blue'
